# Generated by Django 3.2.6 on 2021-09-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carouselImages/')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('slideNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
